# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'
steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  - script: pip install -r requirements.txt
    displayName: 'Install dependencies'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: '<f85c32fe-71d1-4fbe-8d0d-d7feead15970>'
      appType: 'webAppLinux'
      appName: '<your-unique-app-name>'
      package: '.'

